-- =============================================================================
-- Pre-nationals Phase 1 — schema only (competitions, managers, registrations)
-- =============================================================================
-- Introduces a parallel competition pathway alongside the existing ZLTAC event
-- pathway, so the portal can host pre-nationals (and future non-ZLTAC events)
-- without changing the ZLTAC flow. No app code, no API routes, no UI in this
-- phase — those land later.
--
-- Tables added: competitions, competition_managers, competition_registrations.
-- teams gets a competition_id column + an xor check against the existing
-- event_id column so any given team belongs to either a ZLTAC event OR a
-- competition, never both.
--
-- Security model is hybrid (ADR-0002): RLS is the inner perimeter and is
-- enabled here as defence-in-depth, but admin paths (create competition,
-- finalise payment, etc.) will be performed server-side via the service role
-- key in /api/* routes during Phase 2. Self-write paths are admitted at the
-- RLS layer below so authenticated users can still register themselves
-- directly via the anon client, mirroring zltac_registrations.
--
-- Roles: 'pre_nationals_manager' becomes a recognised role value but the
-- roles column is text[], so no enum change is needed. is_competition_manager()
-- below checks membership in competition_managers (not roles), matching the
-- per-competition scoping the spec calls for. Reminder: also extend
-- src/lib/roles.js when Phase 2 wires UI gating.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- 1. competitions
-- -----------------------------------------------------------------------------
-- A competition is an event lifecycle that lives outside ZLTAC's annual cycle.
-- price_per_player is the single per-player fee (no side events or team fees
-- in Phase 1 — added later if/when needed). bank_* mirror zltac_events for
-- payment instructions. payment_info_visible gates whether registrants see
-- those bank fields, same pattern as zltac_events.payments_override.

CREATE TABLE public.competitions (
  id                      uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  slug                    text NOT NULL UNIQUE
                            CHECK (slug ~ '^[a-z0-9-]+$'),
  name                    text NOT NULL,
  start_date              date NOT NULL,
  end_date                date NOT NULL
                            CHECK (end_date >= start_date),
  registration_open_at    timestamptz,
  registration_close_at   timestamptz
                            CHECK (
                              registration_close_at IS NULL
                              OR registration_open_at IS NULL
                              OR registration_close_at >= registration_open_at
                            ),
  price_per_player        numeric(8,2),
  bank_account_name       text,
  bank_bsb                text,
  bank_account_number     text,
  payment_info_visible    boolean NOT NULL DEFAULT false,
  created_by              uuid NOT NULL REFERENCES public.profiles(id),
  created_at              timestamptz NOT NULL DEFAULT now(),
  archived_at             timestamptz
);

CREATE INDEX competitions_slug_idx       ON public.competitions (slug);
CREATE INDEX competitions_active_idx     ON public.competitions (start_date) WHERE archived_at IS NULL;


-- -----------------------------------------------------------------------------
-- 2. competition_managers
-- -----------------------------------------------------------------------------
-- Per-competition grant table. A user with a row here is a manager for that
-- specific competition (cf. is_competition_manager() below). Distinct from the
-- profiles.roles array, which holds org-wide roles — managers are scoped to
-- the one competition they were granted on.

CREATE TABLE public.competition_managers (
  competition_id   uuid NOT NULL REFERENCES public.competitions(id) ON DELETE CASCADE,
  user_id          uuid NOT NULL REFERENCES public.profiles(id)     ON DELETE CASCADE,
  granted_by       uuid REFERENCES public.profiles(id),
  granted_at       timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (competition_id, user_id)
);

CREATE INDEX competition_managers_user_idx ON public.competition_managers (user_id);


-- -----------------------------------------------------------------------------
-- 3. competition_registrations
-- -----------------------------------------------------------------------------
-- One row per (competition, user). payment_reference is generated by the
-- BEFORE INSERT trigger below; amount_owing is set on insert from
-- competitions.price_per_player and is later mutated by payment recording in
-- a future phase. UNIQUE on (competition_id, user_id) prevents duplicates;
-- payment_reference is globally UNIQUE so cross-competition bank statement
-- matching stays unambiguous.

CREATE TABLE public.competition_registrations (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  competition_id      uuid NOT NULL REFERENCES public.competitions(id) ON DELETE CASCADE,
  user_id             uuid NOT NULL REFERENCES public.profiles(id)     ON DELETE CASCADE,
  team_id             uuid REFERENCES public.teams(id) ON DELETE SET NULL,
  payment_status      text NOT NULL DEFAULT 'unpaid'
                        CHECK (payment_status IN ('unpaid', 'partial', 'paid', 'overpaid', 'refunded')),
  amount_paid         numeric(8,2) NOT NULL DEFAULT 0,
  amount_owing        numeric(8,2) NOT NULL DEFAULT 0,
  payment_reference   text UNIQUE,
  registered_at       timestamptz NOT NULL DEFAULT now(),
  UNIQUE (competition_id, user_id)
);

CREATE INDEX competition_registrations_competition_idx
  ON public.competition_registrations (competition_id);
CREATE INDEX competition_registrations_user_idx
  ON public.competition_registrations (user_id);
CREATE INDEX competition_registrations_team_idx
  ON public.competition_registrations (team_id) WHERE team_id IS NOT NULL;


-- -----------------------------------------------------------------------------
-- 4. teams: add competition_id + xor with event_id
-- -----------------------------------------------------------------------------
-- A team now belongs to exactly one of {ZLTAC event, competition}. teams.year
-- does not exist (the column referenced in the original spec); the equivalent
-- link is teams.event_id, which is already nullable (added in
-- 20260502000001_unified_teams_schema.sql without NOT NULL). So no NOT NULL
-- drop is required — we add competition_id and an xor check.

ALTER TABLE public.teams
  ADD COLUMN IF NOT EXISTS competition_id uuid REFERENCES public.competitions(id) ON DELETE CASCADE;

ALTER TABLE public.teams
  DROP CONSTRAINT IF EXISTS chk_teams_event_xor_competition;
ALTER TABLE public.teams
  ADD CONSTRAINT chk_teams_event_xor_competition
  CHECK ((event_id IS NULL) != (competition_id IS NULL));

CREATE INDEX IF NOT EXISTS teams_competition_idx
  ON public.teams (competition_id) WHERE competition_id IS NOT NULL;


-- -----------------------------------------------------------------------------
-- 5. is_competition_manager() helper
-- -----------------------------------------------------------------------------
-- Mirrors is_committee() — STABLE SECURITY DEFINER with search_path pinned to
-- public so the unqualified table lookup can't be hijacked. RLS policies below
-- delegate the "is the caller a manager of this competition?" question here so
-- the manager-set definition lives in one place.

CREATE OR REPLACE FUNCTION public.is_competition_manager(p_competition_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.competition_managers
    WHERE competition_id = p_competition_id
      AND user_id = auth.uid()
  );
$$;


-- -----------------------------------------------------------------------------
-- 6. is_superadmin() helper
-- -----------------------------------------------------------------------------
-- Several policies below want the strict superadmin role (not the wider
-- is_committee() set). Mirrors is_committee()'s shape so the policy predicates
-- stay one-liners.

CREATE OR REPLACE FUNCTION public.is_superadmin()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid()
      AND roles && ARRAY['superadmin']::text[]
  );
$$;


-- -----------------------------------------------------------------------------
-- 7. generate_competition_payment_reference()
-- -----------------------------------------------------------------------------
-- Parallel to public.generate_payment_reference (the ZLTAC version in
-- 20260522000000_simplify_payment_reference.sql). Identical sanitisation +
-- collision-suffix logic, but the year comes from
-- competitions.start_date (EXTRACT YEAR) and the collision scan is against
-- competition_registrations only — each competition has its own bank account,
-- so cross-table reference equality between ZLTAC and a competition is
-- reconcilable.
--
-- Fallback for null/empty alias: USER{short id} so the reference is still
-- unique and recognisable as "the registration whose id starts with XXXX".

CREATE OR REPLACE FUNCTION public.generate_competition_payment_reference(
  p_competition_id uuid,
  p_alias          text,
  p_id             uuid
) RETURNS text
LANGUAGE plpgsql
VOLATILE
AS $$
DECLARE
  v_year     integer;
  v_alias    text := coalesce(p_alias, '');
  alias_part text := substr(upper(regexp_replace(v_alias, '[^A-Za-z0-9]', '', 'g')), 1, 14);
  base_ref   text;
  candidate  text;
  n          integer := 1;
BEGIN
  SELECT EXTRACT(YEAR FROM start_date)::int
    INTO v_year
  FROM public.competitions
  WHERE id = p_competition_id;

  IF v_year IS NULL THEN
    -- Competition row missing or unreadable — refuse rather than emit a
    -- meaningless reference. The caller's INSERT will fail loudly.
    RAISE EXCEPTION 'competition % not found while generating payment reference', p_competition_id;
  END IF;

  -- Empty alias after sanitisation -> {YYYY}USER{short id}. Short id is the
  -- first 8 chars of the registration UUID, which is unique enough to avoid
  -- the collision loop in practice but the loop below still handles ties.
  IF alias_part = '' THEN
    base_ref := v_year::text || 'USER' || substr(replace(p_id::text, '-', ''), 1, 8);
  ELSE
    base_ref := v_year::text || alias_part;
  END IF;

  candidate := base_ref;
  WHILE EXISTS (
    SELECT 1 FROM public.competition_registrations
    WHERE payment_reference = candidate
      AND id <> p_id
  ) LOOP
    n := n + 1;
    candidate := base_ref || n::text;
  END LOOP;

  RETURN candidate;
END;
$$;


-- -----------------------------------------------------------------------------
-- 8. set_competition_payment_reference (BEFORE INSERT trigger)
-- -----------------------------------------------------------------------------
-- Mirrors set_zltac_registration_payment_reference. Only runs when
-- payment_reference is NULL on insert so an explicit value (admin import,
-- backfill) is never overwritten.

CREATE OR REPLACE FUNCTION public.set_competition_payment_reference()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  v_alias text;
BEGIN
  IF NEW.payment_reference IS NULL THEN
    SELECT alias INTO v_alias FROM public.profiles WHERE id = NEW.user_id;
    NEW.payment_reference := public.generate_competition_payment_reference(
      NEW.competition_id, v_alias, NEW.id
    );
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER competition_registrations_set_payment_reference
  BEFORE INSERT ON public.competition_registrations
  FOR EACH ROW EXECUTE FUNCTION public.set_competition_payment_reference();


-- -----------------------------------------------------------------------------
-- 9. set_competition_amount_owing (BEFORE INSERT trigger)
-- -----------------------------------------------------------------------------
-- Default amount_owing from the competition's price_per_player at insert time
-- when the caller didn't pass an explicit value. Coalesce to 0 when price is
-- NULL (committee hasn't priced the competition yet); the row is still
-- creatable. Once payments land in a later phase, an after-payment trigger or
-- API recompute will update amount_owing alongside amount_paid.

CREATE OR REPLACE FUNCTION public.set_competition_amount_owing()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  v_price numeric(8,2);
BEGIN
  IF NEW.amount_owing IS NULL OR NEW.amount_owing = 0 THEN
    SELECT price_per_player INTO v_price
    FROM public.competitions
    WHERE id = NEW.competition_id;
    NEW.amount_owing := coalesce(v_price, 0);
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER competition_registrations_set_amount_owing
  BEFORE INSERT ON public.competition_registrations
  FOR EACH ROW EXECUTE FUNCTION public.set_competition_amount_owing();


-- -----------------------------------------------------------------------------
-- 10. RLS — competitions
-- -----------------------------------------------------------------------------
-- Hybrid pattern (ADR-0002): policies below are defence-in-depth. Admin paths
-- (create, archive, edit price/bank) will run via /api/* using the service
-- role in Phase 2; the INSERT/UPDATE/DELETE policies still admit superadmin
-- directly so the inner perimeter holds even if a future caller forgets to
-- proxy through the API.

ALTER TABLE public.competitions ENABLE ROW LEVEL SECURITY;

-- SELECT: superadmin, managers (their competition), and authenticated users
-- when the registration window is currently open and the row is not archived.
CREATE POLICY "competitions_superadmin_read" ON public.competitions
  FOR SELECT TO authenticated
  USING (public.is_superadmin());

CREATE POLICY "competitions_manager_read" ON public.competitions
  FOR SELECT TO authenticated
  USING (public.is_competition_manager(id));

CREATE POLICY "competitions_open_window_read" ON public.competitions
  FOR SELECT TO authenticated
  USING (
    archived_at IS NULL
    AND (registration_open_at IS NULL OR registration_open_at <= now())
    AND (registration_close_at IS NULL OR registration_close_at >= now())
  );

-- INSERT: superadmin only.
CREATE POLICY "competitions_superadmin_insert" ON public.competitions
  FOR INSERT TO authenticated
  WITH CHECK (public.is_superadmin());

-- UPDATE: superadmin (all rows) or manager (only their own competition).
CREATE POLICY "competitions_superadmin_update" ON public.competitions
  FOR UPDATE TO authenticated
  USING (public.is_superadmin())
  WITH CHECK (public.is_superadmin());

CREATE POLICY "competitions_manager_update" ON public.competitions
  FOR UPDATE TO authenticated
  USING (public.is_competition_manager(id))
  WITH CHECK (public.is_competition_manager(id));

-- DELETE: deliberately not granted. Use archived_at.


-- -----------------------------------------------------------------------------
-- 11. RLS — competition_managers
-- -----------------------------------------------------------------------------

ALTER TABLE public.competition_managers ENABLE ROW LEVEL SECURITY;

-- SELECT: superadmin, the granted user themselves, and other managers of the
-- same competition (so a manager can see their co-managers).
CREATE POLICY "competition_managers_superadmin_read" ON public.competition_managers
  FOR SELECT TO authenticated
  USING (public.is_superadmin());

CREATE POLICY "competition_managers_self_read" ON public.competition_managers
  FOR SELECT TO authenticated
  USING (user_id = auth.uid());

CREATE POLICY "competition_managers_peer_read" ON public.competition_managers
  FOR SELECT TO authenticated
  USING (public.is_competition_manager(competition_id));

-- INSERT/UPDATE/DELETE: superadmin only. Manager grants are an admin act.
CREATE POLICY "competition_managers_superadmin_write" ON public.competition_managers
  FOR ALL TO authenticated
  USING (public.is_superadmin())
  WITH CHECK (public.is_superadmin());


-- -----------------------------------------------------------------------------
-- 12. RLS — competition_registrations
-- -----------------------------------------------------------------------------

ALTER TABLE public.competition_registrations ENABLE ROW LEVEL SECURITY;

-- SELECT: superadmin, managers of the registration's competition, and the
-- registrant themselves.
CREATE POLICY "competition_registrations_superadmin_read" ON public.competition_registrations
  FOR SELECT TO authenticated
  USING (public.is_superadmin());

CREATE POLICY "competition_registrations_manager_read" ON public.competition_registrations
  FOR SELECT TO authenticated
  USING (public.is_competition_manager(competition_id));

CREATE POLICY "competition_registrations_self_read" ON public.competition_registrations
  FOR SELECT TO authenticated
  USING (user_id = auth.uid());

-- INSERT: authenticated user inserts their own row only.
CREATE POLICY "competition_registrations_self_insert" ON public.competition_registrations
  FOR INSERT TO authenticated
  WITH CHECK (user_id = auth.uid());

-- UPDATE: superadmin and managers can update any field on their rows.
-- Self-updates exclude payment_status / amount_paid / amount_owing — those
-- are committee/manager only. Enforced via a row-level WITH CHECK that
-- requires those columns to be unchanged when the caller is the user (and
-- not a manager/superadmin).
CREATE POLICY "competition_registrations_superadmin_update" ON public.competition_registrations
  FOR UPDATE TO authenticated
  USING (public.is_superadmin())
  WITH CHECK (public.is_superadmin());

CREATE POLICY "competition_registrations_manager_update" ON public.competition_registrations
  FOR UPDATE TO authenticated
  USING (public.is_competition_manager(competition_id))
  WITH CHECK (public.is_competition_manager(competition_id));

-- Self-update of non-payment fields only. The WITH CHECK compares NEW.* to
-- OLD.* on the payment columns: the user may update other fields freely, but
-- any change to payment_status / amount_paid / amount_owing is rejected
-- (those go through superadmin/manager policies above, or the service role).
CREATE POLICY "competition_registrations_self_update_nonpayment" ON public.competition_registrations
  FOR UPDATE TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (
    user_id = auth.uid()
    AND payment_status = (SELECT payment_status FROM public.competition_registrations WHERE id = competition_registrations.id)
    AND amount_paid    = (SELECT amount_paid    FROM public.competition_registrations WHERE id = competition_registrations.id)
    AND amount_owing   = (SELECT amount_owing   FROM public.competition_registrations WHERE id = competition_registrations.id)
  );

-- DELETE: superadmin, managers of the competition, registrant themselves
-- (cancel own registration).
CREATE POLICY "competition_registrations_superadmin_delete" ON public.competition_registrations
  FOR DELETE TO authenticated
  USING (public.is_superadmin());

CREATE POLICY "competition_registrations_manager_delete" ON public.competition_registrations
  FOR DELETE TO authenticated
  USING (public.is_competition_manager(competition_id));

CREATE POLICY "competition_registrations_self_delete" ON public.competition_registrations
  FOR DELETE TO authenticated
  USING (user_id = auth.uid());


-- -----------------------------------------------------------------------------
-- 13. Grants
-- -----------------------------------------------------------------------------
-- Default-deny model (ADR-0002): RLS policies alone don't grant table access,
-- we need the underlying GRANT too. Authenticated users get SELECT on all
-- three tables (RLS narrows the rows); only competition_registrations gets
-- INSERT/UPDATE/DELETE for authenticated because that's the only table users
-- write to directly. Admin paths (create competition, grant manager, edit
-- price/bank) go via service_role in /api/*, which has its own default
-- privileges from earlier role-grants migrations.

GRANT SELECT                         ON public.competitions             TO authenticated;
GRANT SELECT                         ON public.competition_managers     TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.competition_registrations TO authenticated;

-- Anon: future "public competition info" page may need SELECT on competitions
-- (similar to zltac_events being anon-readable). Deliberately not granted in
-- Phase 1 — add it in the migration that introduces the public page so the
-- exposure is reviewed alongside the UI that consumes it.
